version: '3'
 
services:
  db:
    image: mysql:8.0
    container_name: mysql8.0cont
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: noeuser
      MYSQL_PASSWORD: noepassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_db_data:/var/lib/mysql
volumes:
        mysql_db_data:
